server:
  port: 9572

spring:
  application:
    name: project-gateway
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:  # 密码（默认为空）
    timeout: 6000ms   # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000    # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10        # 连接池中的最大空闲连接
        min-idle: 5         # 连接池中的最小空闲连接
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: project-config
    gateway:
        discovery:
          locator:
            enabled: true
        routes:
          # 认证中心
          - id: project-auth
            uri: lb://project-auth
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1
          #system 模块
          - id: project-system
            uri: lb://project-system
            predicates:
              - Path=/system/**
            filters:
              # 限流配置
              - StripPrefix=1
          #player 玩家
          - id: project-player
            uri: lb://project-player
            predicates:
              - Path=/player/**
            filters:
              # 限流配置
              - StripPrefix=1
          #gen 代码生成器
          - id: project-gen
            uri: lb://project-gen
            predicates:
              - Path=/gen/**
            filters:
              # 限流配置
              - StripPrefix=1
          #games games
          - id: project-games
            uri: lb://project-games
            predicates:
              - Path=/games/**
            filters:
              # 限流配置
              - StripPrefix=1
          #agency 代理
          - id: project-agency
            uri: lb://project-agency
            predicates:
              - Path=/agency/**
            filters:
              # 限流配置
              - StripPrefix=1
          #hall
          - id: project-hall
            uri: lb://project-hall
            predicates:
              - Path=/hall/**
            filters:
              # 限流配置
              - StripPrefix=1
          #order 订单
          - id: project-order
            uri: lb://project-order
            predicates:
              - Path=/order/**
            filters:
              # 限流配置
              - StripPrefix=1
          #customer 客服
          - id: project-customer
            uri: lb://project-customer
            predicates:
              - Path=/customer/**
            filters:
              # 限流配置
              - StripPrefix=1

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms